### ISSUE TITLE
Improve TiddlyMap source compilation

### ISSUE THREAD

**Issue by felixhayashi** [felixhayashi/TW5-TiddlyMap#200] opened 2016-01-07 01:06 UTC
If other people are interested in the project and want to play with the source code, they should be able to compile it and create a tw-plugin eventually that can be tested.

Requires turning tmap into a npm package and specifying dependencies for the gulp file.

**Comment by flibbles** [comment] 2016-01-15 17:00
I'll just drop my notes on my attempt to compile TiddlyMap here. These things will probably need to be addressed at some point during improvement. There's no rush on any of these. It's just to help make a list before I forget what I've already learned.

1. The clean tasks in the gulp file will either need to be updated to correspond with the changed behavior in the 'del' build module, or documentation will need to specify V1 of 'del'. Currently, if someone uses npm to install 'del' without specifying a version, their gulp build will exit after cleaning and not give any indication why. To bring the gulp files up to date, the following change needs to be made:
```
gulp.task("clean", function (cb) {

  var options = { force: true };
  del([ "../dist/"/*, "../docs/"*/ ], options, cb);

});
```
should become...
```
gulp.task("clean", function () {

  var options = { force: true };
  return del([ "../dist/"/*, "../docs/"*/ ], options);

});
```
This is to compensate for changed behavior in 'del' V2. [This forum](http://stackoverflow.com/questions/32605090/gulp-clean-del-behaviour-has-changed) goes into better detail. Hotzone and TopStoryView and stuff will probably want to change over eventually too.

2. The documentation will have to specify an older version of gulp-sass (I'm not sure which), at least for now. gulp-sass uses libsass, which seems to have regressive bug in it that causes it to mess up when it reads `plugins/felixhayashi/tiddlymap/files/layout.scss`. Specifically, it's this part right here:
```css
@media (max-width: unquote("{{$:/themes/tiddlywiki/vanilla/metrics/sidebarbreakpoint}}")) {
  .tc-sidebar-scrollable {
    .tmap-desktop-editor {
      display: none;
    }
  }
}
```

Specifically, it's the unquote part. The libsass chokes on the parenthesis in the string. I don't see why this wouldn't be valid scss, and libsass has many bug reports in it that are similar to this, and all of them are regressions.

That's it for now. After dealing with those, I succeeded in making a build, although my dist directory ended up looking entirely different from what it currently does, which will make an interesting problem when it comes to making a pull request. I am curious as to why the dist directory is checked in to git. I'm sure there's a reason, but as generated code, it seems like it'll get problematic if other people start working on the source. But that's another topic altogether.

**Comment by flibbles** [comment] 2016-01-15 17:17
I didn't actually confirm that the problem is in libsass, but here are some libsass bugs that seem possibly related. ([This one](https://github.com/sass/node-sass/issues/1070) and [this one](https://github.com/sass/node-sass/issues/1217)). Neither of those are specifically this problem, but they indicate to me that libsass suddenly sucks at strings. This should probably be confirmed as a libsass problem, and maybe a bug should be submitted.

**Comment by felixhayashi** [comment] 2016-01-15 19:27
> I'll just drop my notes on my attempt to compile TiddlyMap here

Thanks @flibbles for sharing this, highly appreciated. I will consider your input as soon as I find the time to deal with this issue! Sorry for this hassle.

> Specifically, it's the unquote part. The libsass chokes on the parenthesis in the string.
> This should probably be confirmed as a libsass problem, and maybe a bug should be submitted.

You are right. I noticed that too. I even opened an issue at the sass repo a few days ago (https://github.com/sass/sass/issues/1957) but it was rejected. One person there told me that a workaround would be to use ruby sass which behaves as expected in conjunction with customized at-rules which are later replaced. You'll see what I mean when I check in the new gulp script next time.

> This is to compensate for changed behavior in 'del' V2. This forum goes into better detail. Hotzone and TopStoryView and stuff will probably want to change over eventually too.

:+1:

**Comment by felixhayashi** [comment] 2016-01-16 13:41
@flibbles Working on a better compilation process at the moment and will add it together with the new release.

**Comment by felixhayashi** [comment] 2016-01-19 16:58
Hi @flibbles, it took some time but I now completely revised the build process and the docs ;)

I uploaded everything to the `develop` branch, so you need to switch to the `develop` branch at GitHub to see the changes. Could you give it a try? I described all the steps necessary regarding build and contribution in the `README.md` (`develop` branch) and it would be great if you could follow the steps to do your PR and tell me if everything works as expected and is adequately described.

Thanks!

**Comment by flibbles** [comment] 2016-01-19 20:18
The build works seemlessly. The instructions were clear and there were no hiccups. The only thing I can see that could possibly be improved is that `dist/felixhayashi/tiddlymap/files/layout.css` is being tracked when it regenerates with each build (and is different between production and test builds). There might be a reason for this, so I only mention it.

I'll sign the CLA and make the pull request. You want it on `develop`?

**Comment by felixhayashi** [comment] 2016-01-19 22:09
> The build works seemlessly. The instructions were clear and there were no hiccups. 

Great, thanks for the feedback.

>  The only thing I can see that could possibly be improved is that dist/felixhayashi/tiddlymap/files/layout.css is being tracked when it regenerates with each build (and is different between production and test builds). There might be a reason for this, so I only mention it.

That is strange, the changed files in dist should not be tracked unless explicitly added using `git add`. I'll have a look at it once I find the time.

> I'll sign the CLA and make the pull request. 

Thanks merged it.

> You want it on develop?

Yap, as soon as you find the time.

**Closed** 2016-02-02 23:54 UTC
Labels: important, meta, resolved in next release
