### ISSUE TITLE
Font color issue (possibly)

### ISSUE THREAD

**Issue by ed-n1n2** [felixhayashi/TW5-TiddlyMap#113] opened 2015-04-17 23:29 UTC
I have tags with associated icons that are rendered in the map, but have their captions (IIRC) as white text against a white background. Bug, or possible additional parameter to be configured?

Current version of TiddlyMap with TiddlyWiki 5.1.7.

**Comment by felixhayashi** [comment] 2015-04-18 08:08
Hi @ed-n1n2 

could you please post a screenshot? thanks

-Felix

**Comment by felixhayashi** [comment] 2015-06-14 19:49
Could not reproduce the error with your setup and will close this now. 
Please reopen if it still occurs.

**Closed by felixhayashi** 2015-06-14 19:49 UTC
Labels: bug, unconfirmed
