### ISSUE TITLE
Nodes appear in arbitrary positions even when float is turned off.

### ISSUE THREAD

**Issue by rcrath** [felixhayashi/TW5-TiddlyMap#91] opened 2015-04-01 02:56 UTC
context: live view
Maybe this is me misunderstanding something, but I would expect that unchecking the "floating" nodes would mean that nodes remember their position so I can lay out a tree, travel down a branch with one step or more neighbor scope on, then come back and find my first tree in the layout in which I had arranged it. 

Instead, I see no discernable difference between checked and unchecked.  Both let the nodes float, which looks cool, and both reorder the graph's layout arbitrarily, and change every time the graph is returned to. 

 It would be great if there were a default behavior to the graph that laid out the outgoing edges in order from start to end of the document, say by beginning with the first link in the focused tiddler at 12 o'clock and proceeding around the radius clockwise with outgoing links first and incoming links later. If there is a parent link by way of which the present node was navagiated to, that could be last (i.e. 11 o'clock).  This way the layout would have consistency.  It would be great if it remembered arbitrary layouts too so I can sort links in whatever way makes most sense as way of restructuring my thinking within a tiddler.  As it is, I can reorganize but when I move the focus away and come back, the reorg is lost.

**Comment by rcrath** [comment] 2015-04-01 04:38
I just discovered "save positions" in the menu, but using it did not have any effect.  Positions were still reordered when I navigated away and came back.

**Comment by felixhayashi** [comment] 2015-04-01 13:07
Hi @rcrath 

> Maybe this is me misunderstanding something, but I would expect that unchecking the "floating" nodes would mean that nodes remember their position so I can lay out a tree, travel down a branch with one step or more neighbor scope on, then come back and find my first tree in the layout in which I had arranged it. 

Disabling "Floating nodes" means that once the graph stabilized, nothing will move anymore. It does not work that well  at the moment and I am waiting for vis.js 4.0 whether they fixed it there.

> It would be great if there were a default behavior to the graph that laid out the outgoing edges in order from start to end of the document, say by beginning with the first link in the focused tiddler at 12 o'clock and proceeding around the radius clockwise with outgoing links first and incoming links later

Sadly, I cannot control that. :(

>  It would be great if it remembered arbitrary layouts too so I can sort links in whatever way makes most sense as way of restructuring my thinking within a tiddler. As it is, I can reorganize but when I move the focus away and come back, the reorg is lost.

Yes, I feel the same about this. The problem is, it is not possible by design because a node may appear in different contexts and I cannot save positions of the live view because the contexts always change - a node may appear at the bottom in a certain graph and in the next time be at the top because it is part of another relationship. If I would fix positions for one constellation, it would look strange in another and keeping track of all the existing constellations is impossible :(

**Comment by rcrath** [comment] 2015-04-01 22:08
Got it.

**Comment by rcrath** [comment] 2015-04-02 23:34
THis seems to have improved somewhat with the last update...

**Comment by felixhayashi** [comment] 2015-04-03 00:19
Hmm, well if nodes also appeared in the previous context and now appear in the current context of the live view, they will keep their positions. But when a node is removed from the context (e.g. by scrolling down and node is not a neighbour anymore), the position is lost... I think this is what you are referring to.

**Comment by rcrath** [comment] 2015-04-03 05:29
@felixhayashi wrote:
>I cannot save positions of the live view because the contexts always change - a node may appear at the bottom in a certain graph and in the next time be at the top because it is part of another relationship. If I would fix positions for one constellation, it would look strange in another and keeping track of all the existing constellations is impossible :(

hmmm, would it be possible to have some kind of cookie based system so a view gets a cookie that stores layout info on the assumption not all configs need to be stored, just ones that are returned to.  It is only a small set that I care about the layout for, usually 1 and two step nearest neighbors on the base page for a particular project.  That would reduce the problem by an order of magnitude as far as the combinatorial sprawl I think, no?  I think this is the idea of Bayesian stuff too, just work with what is working rather than the whole set.

I don't need them to stay put across contexts, just within particular contexts, and actually only a few "hubs" at that.  E.G.,  I have a project called history of hearing, and I generally start what ever note taking work I do from the central hub page for that project, which has about two dozen links.  If I could save postions for that view at one step scope in a cookie or someother way, and maybe another for two step scope I would be happy.  When the context switches, everything can go where it will, as long as it comes back to the way I sorted it in that particular context or two.  Thus it would not require all possible combinations, just the ones that are A hubs, or B manipulated in some way by the user. 

In the history of hearing project, this entails pulling the "link to" source, the parent node of the project, in this case called worknotes, out of the main complex so that other projects don't get mixed in on a two-step scope.  Most other pages have between 0-3 links and are thus much more manageable at a glance.  When a hub page comes back in a different order every time, it gets confusing though because there are more links than the magic number range of four two seven, so everything cannot be taken in as a whole.  That is the situation when layout helps find things, so maybe there could be an outgoing link threshold (outbound links >4>) under which the cookies or whatever would not work.  

ANyway, if the answer is still that it is a constraint of viz, that is fine, I am just brainstorming since having some kind of layout consistencyon hub pages would be a big help.  

Finally, if everything stays the same, shouldn't the "save postion" dropdown be grayed out in live view?

**Comment by felixhayashi** [comment] 2015-04-03 13:13
Hi @rcrath 

just to summarize this for me your goal is, if I understood you correctly, to have each tiddler on the left side accompanied with a graph on the right side *that remembers the positioning on a per tiddler context*.

Imo is a valid use case, so I will have a close look if and how this is possible. However, this would definitely come with some drawbacks.

* If a new relationship is somehow added, it has to be manually positioned because the position that is automatically assigned (if no position is found in store) may look ugly among the existing nodes with fixed positions.
* Storing positions per constellation will of course make your file a bit larger, however, I think this is not a real problem unless you have an extremely large wiki.
*..

-Felix

**Comment by felixhayashi** [comment] 2015-04-03 13:13
> I just discovered "save positions" in the menu, but using it did not have any effect. Positions were still reordered when I navigated away and came back.

You were right here, it did not work for neighbours. I'll change that

**Comment by rcrath** [comment] 2015-04-05 21:04
@felixhayashi summarized as follows:
>just to summarize this for me your goal is, if I understood you correctly, to have each tiddler on the left side accompanied with a graph on the right side that remembers the positioning on a per tiddler context.

It would not need to remember a context because it was visited however.  only remember if the user manipulates the graph.  It would be fine with me if new stuff added to a manipulated graph came in looking awkward, since it is already a graph I am manually manipulating anyway.  If a graph is not manipulated it means either it was not interesting or else it was simple enough to take in at a glance (i.e. links =<7) and thus the ordering did not matter.

**Comment by felixhayashi** [comment] 2015-04-05 22:03
Ah ok, thanks for this explanation.

I need some time to analyse whether or how this can be done because the current way of handling graphs and their positions does not support stuff like that at all. So it might take a while or in the worst case is not possible... But I'll try to do it and inform you on this matter if I made any progress.

-Felix

**Comment by rcrath** [comment] 2015-04-07 02:01
great, thanks.

**Comment by felixhayashi** [comment] 2015-04-17 13:13
@rcrath 

TiddlyMap now saves the positions in the live view automatically per focussed tiddler if you disabled floating nodes and drag a tiddler (or if you click "save positions"). Could you please verify if it works as expected? Please note that nodes will always float (even if disabled) until the graph stabilized.

-Felix

**Comment by rcrath** [comment] 2015-04-19 09:18
It seems to be working with today's update.  was skittish before.  still checking things out.  I just noticed that although it saves positions in a session, when the whole wiki is reloaded, the positions are lost.

**Comment by felixhayashi** [comment] 2015-04-19 09:37
Hi @rcrath 

> I just noticed that although it saves positions in a session, when the whole wiki is reloaded, the positions are lost. 

Yes, i'll fix that. Sorry.

**Comment by felixhayashi** [comment] 2015-04-19 13:03
@rcrath should work now

**Comment by felixhayashi** [comment] 2015-06-07 13:01
Hi @rcrath.
I'll close this now. If this is still an issue. Let me know..

**Closed by felixhayashi** 2015-06-07 13:01 UTC
Labels: optimization

**Comment by felixhayashi** [comment] 2015-08-09 13:14
Hi @rcrath 

I just posted a description of a technique in the tiddlywiki groups that explains (+code) how you can open predefined views in the sidebar when tiddlers are focussed. I think it is related to your case and maybe it is useful for you.

https://groups.google.com/d/msg/tiddlywiki/JTHkT9TvhUY/THYjDKaQAwAJ

-Felix
