### ISSUE TITLE
Cannot close welcome dialog on firefox quantum

### ISSUE THREAD

**Issue by khia** [felixhayashi/TW5-TiddlyMap#273] opened 2017-12-24 13:44 UTC
There is no way to close the welcome dialog

**Comment by felixhayashi** [comment] 2017-12-31 12:15
Thanks for reporting @khia, I will investigate the issue the next days.

**Comment by felixhayashi** [comment] 2018-01-04 19:28
Hi @khia I cannot reproduce this. Will close this, if this continues to be an issue, please be more specific about the steps that lead to the problem.

**Closed by felixhayashi** 2018-01-04 19:28 UTC
Labels: doesn't work, unconfirmed
