### ISSUE TITLE
TiddlyMap does not work with TiddlyDesktop

### ISSUE THREAD

**Issue by TheCoconutChef** [felixhayashi/TW5-TiddlyMap#261] opened 2017-03-13 13:46 UTC
After having installed [TiddlyMap](tiddlymap.org) through firefox using the drag and drop method, [TiddlyDesktop](https://github.com/Jermolene/TiddlyDesktop) is unable to open the tiddly file due to a javascript error. One gets the following message:

>Internal JavaScript Error
>Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
>Uncaught TypeError: undefined is not a function

after which one cannot interact with the tiddly file.

The tiddly file works when using firefox and chrome. The error only shows up in TiddlyDesktop.

**Comment by felixhayashi** [comment] 2017-03-18 21:21
Hi @TheCoconutChef,

thanks for reporting. I do not TiddlyDesktop and therefore cannot really offer support on this issue. I guess the only option is to use TiddlyWiki + TiddlyMap in a normal browser. Sorry :(

**Comment by felixhayashi** [comment] 2017-12-08 09:47
Seems like drag and dropping the TiddlyMap plugin does not work with TiddlyDesktop, it displays shows "undefined" in the `$:/import` tiddler. I'll investigate a bit here.

**Comment by felixhayashi** [comment] 2017-12-08 10:11
Seems not to be caused by TiddlyMap but it's an issue with TiddlyWiki's import mechanism: https://github.com/Jermolene/TiddlyWiki5/issues/3044

**Comment by felixhayashi** [comment] 2018-09-16 20:31
As noted by @Jermolene

> Hi @felixhayashi I think this is a manifestation of the cross browser drag-and-drop problems; I find that one can only reliably drag tiddlers between instances of the same browser. The workaround is to export the plugins as JSON files and then use drag and drop from the filesystem into TiddlyDesktop to install them.

So I will add an entry to the docs that explains this procedure and then close this issue as solved.

**Comment by felixhayashi** [comment] 2018-10-06 22:32
> So I will add an entry to the docs that explains this procedure and then close this issue as solved.

see http://tiddlymap.org/#Common%20Pitfalls

**Closed by felixhayashi** 2018-10-06 22:32 UTC
Labels: not nice, upstream
