### ISSUE TITLE
HTML file size concern

### ISSUE THREAD

**Issue by QubitPi** [felixhayashi/TW5-TiddlyMap#376] opened 2020-09-30 21:58 UTC
Hello, I am using TiddlyRoam Desktop, which I think is a fantastic app I love.

I'm having notes in a HTML file that is more than 30,000 lines and will reach to about 100,000 lines in the next couple of weeks.

In addition, I have another HTML file that is supposed to go infinitely long, because I'm reading everyday and all my notes goes there...a lot of notes

So my question is, are we going to split the file?(I guess we have to because the file is just too big, and the graph is already taking more than 5 secs to refresh) If so, how are we going to split the existing giants?

**Comment by felixhayashi** [comment] 2020-10-03 19:30
Hi @QubitPi 

TiddlyMap is not designed to hold more than 100 nodes per map.Try to keep your maps small. Small maps are faster to process by TiddlyMap and are generally easier to work with. If a map becomes to big, try to outsource nodes into another view or change your node filters.

>So my question is, are we going to split the file?

You need to decide this for your case but If you split a wiki, the problem is that you cannot link tiddlers anymore. but if your file becomes bigger than 100mb maybe there is no other option.

**Comment by linonetwo** [comment] 2021-04-19 06:28
Hi, tiddlymap will be very slow for huge tiddlywiki https://github.com/felixhayashi/TW5-TiddlyMap/issues/391

So it should needs split wiki, or refactor tiddlymap.

**Comment by flibbles** [comment] 2022-09-06 16:50
I'm going to close this issue out. Reducing the size of your tiddlywiki isn't really a TiddlyMap concern. I will give these pointers though.

* You can use TW5-Uglify to trim down the core and any plugins you have.
* TiddlyMap can now be switched to using vis-network instead of vis.js. This will remove half a megabyte from your file.
* TiddlyWiki has mechanisms to separate plugins and core code from the tiddlywiki itself, thus splitting your file in a way such that TiddlyMap will still continue to function as expected.
* I don't recommend you use TiddlyWiki's lazy loading mechanims. It's bad.
* If file size is still an issue, you may consider switching to Node.js, which allows you to keep your tiddlywiki divided into a directory of separate files per tiddler. For very large projects, I'd recommend everyone do this anyway.

Hope this help!

**Closed by flibbles** 2022-09-06 16:50 UTC
Labels: question
