### ISSUE TITLE
Make title fields wider or always show text fields not only on hover

### ISSUE THREAD

**Issue by UtopistList** [felixhayashi/TW5-TiddlyMap#429] opened 2022-09-30 22:47 UTC
The issue is described here:
https://groups.google.com/g/TiddlyWiki/c/B2urf1QpAv0

**Comment by flibbles** [comment] 2022-10-01 01:38
I'm really unclear as to what exactly you're trying to accomplish. You want the tiddler's text to appear on the graph in place of the title?

Are you aware that in the TiddlyMap global configuration, in the "Field Settings" tab, you can set the "Node-label field" to text to have a tiddler's text used as the node label. Is that what you're looking for?

**Comment by flibbles** [comment] 2022-10-01 02:06
If it's about making the nodes wider so they fit more, look at this issue: https://github.com/felixhayashi/TW5-TiddlyMap/issues/383

**Comment by UtopistList** [comment] 2022-10-01 10:14
Thanks.
Yes.
That's already a good solution.
Or, to simply allow the title fields to be wider.
Can they be made resizeable by dragging?

**Comment by flibbles** [comment] 2022-10-01 13:04
They cannot. This is a TiddlyWiki limitation. Title fields are not supposed to ever contain newline characters, so only allowing a single line for them is a logical limitation.

**Comment by UtopistList** [comment] 2022-10-01 13:47
Ah, so that's why I am getting long column shaped title fields when I paste
a long text as the title.
I am having difficulties understanding the law, so I use TiddlyWiki to
visualise laws, so I have to create a map of full law paragraphs with
annotations, and relations, highlights, etc.
That's how I encountered this problem.
Hopefully using the tiddler's text as the node label can eliminate this
problem.
You could try to make a map of laws yourself, to see if you encounter
issues.
Thanks!

**Comment by flibbles** [comment] 2022-10-01 21:08
I could try this myself, but I still am unsure what the problem is. Using the text body as a label is not at all something TiddlyMap expects. the underlying vis-network renderer has only limited support for markup in node labels (bold, italics, newline characters, and that's it, I think).

I set text as node-label for a project of mine, and it seems to work about as well as could be expected, considering this is guaranteed to flood the graph with enormous nodes. I recommend using hard linebreaks. That seems to make it a little more useful. That's when you wrap your text in `"""` on its own line. Or if you're wrapping the entire body, you can put it on just the first line like this:
```
"""
These are paragraphs

These will render better'ish.
```

As for making the nodes wider instead of longer, like I said, check out https://github.com/felixhayashi/TW5-TiddlyMap/issues/383 where I have instructions on how to do that.

**Comment by flibbles** [comment] 2022-10-04 20:06
I'm going to close this out unless you have any further questions.

**Closed by flibbles** 2022-10-04 20:06 UTC
