### ISSUE TITLE
Full screen does not work properly from sidebar

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#25] opened 2015-01-09 15:47 UTC
I love the new full-screen feature as much as I hate the position of the main editor. And this issue combines both to make me a super hater: you can view anything in fullscren except the main editor. The screen is filled just half. See screenshot below from chrome on windows

![image](https://cloud.githubusercontent.com/assets/2270425/5682231/af5e9e2a-981e-11e4-96b6-33bdb1d5840c.png)

The full screen feature is a key feature to properly display and edit maps, so I think this should be an important fix.

I want to say also that I find odd where the editor is: the sidebar. Sidebars are for table of contents and some side information, not for holding an editor. I really feel uncomfortable using it. I used to end with my head inclined to the right. Maybe it is useful in a 24" screen, but not for average users I think. Could you at least provide a button to open the editor in a tiddler?

**Comment by tobibeer** [comment] 2015-01-09 17:30
> Sidebars are for table of contents and some side information, not for holding an editor

I think, especially for "diving mode", the sidebar is a perfect place.

Not sure, but I think you can always create a TiddlyMap tiddler that transcludes the sidebar tab. Done.

**Comment by danielo515** [comment] 2015-01-09 18:48
Dear @tobibeer 

> Not sure, but I think you can always create a TiddlyMap tiddler that transcludes the sidebar tab. Done

Do you really think the average user will do this? You have created many customizations that makes other trivial task easier. This is easy for us, not for everyone. In fact, is even uncomfortable for me, because I have to remember how to do this on every new TW

**Comment by felixhayashi** [comment] 2015-01-09 20:03
Hi guys,

> I think, especially for "diving mode", the sidebar is a perfect place.

What tobi says here is what I think too, the sidebar is perfect because it is fixed and no matter how far you scroll down, you can always see the connections on the right. I am developing a plugin at the moment that will trigger the "diving" (seeing neighbors) automatically when a tiddler is scrolled to. Also for drag'n'drop it is the right place. Moreover, the editor is not really part of the content like tiddlers are.

> In fact, is even uncomfortable for me, because I have to remember how to do this on every new TW

The problem is, I have to make a decision where to put the main editor and for the reasons mentioned, I really think the sidebar is the suitable place. Having two places for the main editor will confuse users.

But Danielo, it is really easy to create an editor in a tiddler. Just add

    <tiddlymap height="400px" editor="advanced"></tiddlymap>

to a tiddler of your choice (without view="..."). Done.

> The screen is filled just half. See screenshot below from chrome on windows

This is really strange. It works fine in firefox 34 and chrome 39... Which browser are you using? Could you open the browser console then open the editor in fullscreen and post the debug log please?

-Felix

**Comment by tobibeer** [comment] 2015-01-09 22:16
What Danielo posted is the same thing I was referring to: https://github.com/felixhayashi/TW5-TiddlyMap/issues/21#issuecomment-69040155

@danielo515, wait a a tiny moment for some documentation to appear... then, using that **$tiddlymap** widget should be an easy thing to do... if not frequent in terms of embedding a special view in a tiddler, etc... perhaps even wrapped in a macro simplifying things yet more.

**Comment by danielo515** [comment] 2015-01-10 09:09
This is all I get


```
@MAIN_EDITOR Toggle fullscreen
$:/plugins/felixhayashi/tiddlymap/caretaker.js:21 @MAIN_EDITOR Adding fullscreen markers
$:/plugins/felixhayashi/tiddlymap/caretaker.js:21 @MAIN_EDITOR Repainting the whole graph
$:/plugins/felixhayashi/tiddlymap/caretaker.js:21 @MAIN_EDITOR Toggle fullscreen
```

pretty normal I think. My chrome version is Version 39.0.2171.95 m on windows 7.

In firefox it works nicely. Strange

**Comment by felixhayashi** [comment] 2015-01-10 12:54
Thanks @danielo515,

The log really seems fine. I changed some css now. could you please test it again?

http://felixhayashi.github.io/TW5-TiddlyMap/index.html (0.6.4+904)

-Felix

**Comment by tobibeer** [comment] 2015-01-10 14:46
@felixhayashi, I don't get the problematic behavior anymore. Fullscreen now seems to work properly in both sidebar and story.

**Comment by felixhayashi** [comment] 2015-01-10 16:48
nice thanks for telling me tobi

**Comment by andtheWings** [comment] 2015-02-05 03:52
I'm getting the full-screen bug too when I press full-screen from side-bar in Chrome 40 on Windows 7. Nothing really on the console:

@MAIN_EDITOR Toggle fullscreen
@MAIN_EDITOR Adding fullscreen markers
@MAIN_EDITOR Repainting the whole graph
@MAIN_EDITOR Removing fullscreen markers
@MAIN_EDITOR Repainting the whole graph

**Comment by felixhayashi** [comment] 2015-02-05 09:27
Hi @andtheWings,

> I'm getting the full-screen bug too when I press full-screen from side-bar in Chrome 40 on Windows 7. 

Thanks for telling me and posting the debug. Could you tell me exactly what doesn't work or post a screenshot?

**Comment by tobibeer** [comment] 2015-02-05 11:54
Seems to be back for me as well... but I get a different log.

<<<
These tiddlers changed: Object {$:/temp/focussedTiddler: Object}
@MAIN_EDITOR Toggle fullscreen
@MAIN_EDITOR Adding fullscreen markers
@MAIN_EDITOR Repainting the whole graph
These tiddlers changed: Object {$:/temp/focussedTiddler: Object}
<<<

**Comment by felixhayashi** [comment] 2015-02-05 12:19
Ok I will check that. Maybe this is because I added the `tmap-` prefix for all the classes lately. This is what I was afraid of (stuff crashes after this change) :scream:

**Comment by tobibeer** [comment] 2015-02-05 14:13
perhaps, should be easy to find then :octocat:

**Comment by felixhayashi** [comment] 2015-02-07 20:56
yesss crazy bug. Turns out: Media queries on smaller screens override my css "left" value.

**Comment by felixhayashi** [comment] 2015-02-07 21:09
should work now ;)

**Comment by danielo515** [comment] 2015-02-11 07:52
Ok. It works now for me. Thank you very much!

**Comment by tobibeer** [comment] 2015-02-11 08:02
dito, works as expected... thanks a lot for fixing

**Comment by felixhayashi** [comment] 2015-02-11 10:22
Thanks guys, then I will close this now! Finally!

**Closed by felixhayashi** 2015-02-11 10:22 UTC
