### ISSUE TITLE
TM tiddler toolbar button suggestions (split, create missing tiddlers, close popups)

### ISSUE THREAD

**Issue by danielo515** [felixhayashi/TW5-TiddlyMap#171] opened 2015-10-01 17:17 UTC
Hello @felixhayashi ,

Since Magic-Edge feature appeared, the first thing I do when I use TWmap in any wiki is to create some: Link from here buttons, with certain presets. This button creates a new tiddler "pointing" or related to the current one. This significantly increases the efficiency, because I don't have to worry about creating a new tiddler, and then coming back to the original one and link it, typing it's name first in most of the cases.

 It would be cool if tiddly-map provides such feature by default. The current popup is very small and it does not display much information, so you are forced to search by typing. Probably the worst part is that it requires that the destination tiddler exists. Being able to create it directly will increase usability, as I said.

Regards

**Comment by felixhayashi** [comment] 2015-10-02 08:13
Hi Danielo

thanks for mentioning this :)

You do not mention what popup you are talking about. I assume we are talking about the dropdown in the tiddler toolbar? Because there is also the editor toolbar.

> It would be cool if tiddly-map provides such feature by default. […] Probably the worst part is that it requires that the destination tiddler exists. Being able to create it directly will increase usability, as I said.

The problem is that I cannot overload the dropdown popup. But maybe what I could do is when you search for a tiddler you want to link to and the title is not found (because it doesn't exist), it will not display "No results" but show a button that says something like "create tiddler and link to tiddler".

**Comment by danielo515** [comment] 2015-10-02 14:26
>thanks for mentioning this :)
Thanks to you!

> You do not mention what popup you are talking about. I assume we are talking about the dropdown in the tiddler toolbar? Because there is also the editor toolbar.

Yes, your assumption is correct. Sorry.

>"No results" but show a button that says something like "create tiddler and link to tiddler".
I was thinking in something like that. I think it fits perfectly many usage scenarios.

> The problem is that I cannot overload the dropdown popup.
I was not thinking about including the mentioned buttons in the drop-down, but in the tiddler toolbar. As you know, you can select which buttons are displayed on the tiddler toolbar.
Something specially annoying is that you have to click the button to close again the dropdown popup, that's why I don't use it. That fact, along with it's size really  stress me, seriously, is hard to describe. That's why I was asking also for other simpler buttons as link from here

**Comment by felixhayashi** [comment] 2015-10-02 15:40
> That fact, along with it's size really stress me, seriously, is hard to describe. 

I am sorry, this is stressing you. I also don't like the fact that it doesn't close (see this issue I once created: https://github.com/Jermolene/TiddlyWiki5/issues/1497). But you are right, I'll change this in the next release.

> I was not thinking about including the mentioned buttons in the drop-down, but in the tiddler toolbar. 

Ah ok.

> That's why I was asking also for other simpler buttons as link from here

At the moment, the popup is highly compact and it really makes sense. It took much time to develop it (https://github.com/felixhayashi/TW5-TiddlyMap/issues/19). The problem with two buttons is that it uses more space of the toolbar and people will hate me for that as the space is valuable and very limitet :D

What should I remove of the current dropdown in your opinion?

1. You need to specify the type of the relationship so you need a selectbox.
  * What if a new relationship should be created instead of choosing an existing type? You need a text input near the selectbox
2. Which tiddler to link to? Textfield that allows you to search.
3. Which links already exist and maybe you want to delete some of them? So you need a list of connections.

I am guessing: You want to separate 1+2 from 3? That would be reasonable but again, two buttons in the toolbar and people will kill me…

So please wait for my implementation and then we can discuss it again.

**Comment by danielo515** [comment] 2015-10-02 16:01
>I am sorry, this is stressing you. I also don't like the fact that it doesn't close (see this issue I once created: Jermolene/TiddlyWiki5#1497). But you are right, I'll change this in the next release.

Not your fault, don't feel guilty. 

> Ah ok, then I misunderstood you.

I was trying to say that I like BOTH solutions.

>At the moment, the popup is highly **compact** and it really makes sense. 

That is the point that does not makes sense **compact**

> What should I remove of the current dropdown in your opinion?

Nothing! It has all the required information, but it is too compressed. You could add a configuration to open it in a modal rather than a popup. You know already what I think about popups :tongue: 

> two buttons in the toolbar and people will kill me…

Not in the sidebar, but the tiddler's toolbar. As you know, you can select which buttons you want to display.

**Comment by felixhayashi** [comment] 2015-10-02 18:26
I implemented a popup killer that closes the popup when clicked outside.

Also I added what I described before

> But maybe what I could do is when you search for a tiddler you want to link to and the title is not found (because it doesn't exist), it will not display "No results" but show a button that says something like "create tiddler and link to tiddler".

Please give it a try at http://tiddlymap.org, I think it does what you want :)

I'll also consider splittin the big popup into two smaller popups in the toolbar. But I of course need to plan this first.

<img src="https://cloud.githubusercontent.com/assets/4307137/10254400/ba7ad9ee-6943-11e5-82d0-80a89f984882.png" width="45%"></img> <img src="https://cloud.githubusercontent.com/assets/4307137/10254404/be0c81e8-6943-11e5-9d4c-76e9e7359ed7.png" width="45%"></img> 

-Felipe

**Comment by felixhayashi** [comment] 2015-10-18 13:58
Did you try it out at http://tiddlymap.org @danielo515? The popup is still big but you can now create links to non-existent tiddlers. I'll close this issue now and will continue to think about how to make the dropdown smaller or offering a two separated buttons.

**Closed by felixhayashi** 2015-10-18 13:58 UTC
Labels: improvment

**Comment by danielo515** [comment] 2015-10-19 08:53
Hello @felixhayashi 
I tried, and I failed:

![image](https://cloud.githubusercontent.com/assets/2270425/10573416/9ef82c4e-764f-11e5-921f-790c91260a88.png)

**Comment by felixhayashi** [comment] 2015-10-19 12:00
wtf? Wait a second pls I'll fix it

**Comment by felixhayashi** [comment] 2015-10-19 12:10
fixed now :)

**Comment by danielo515** [comment] 2015-10-19 14:42
What would be cool is to be able to define which template to use for the newly created tiddler. This is an important lack of tiddlymap and would help on creating hierarchical layouts.

Regards

**Comment by felixhayashi** [comment] 2015-10-19 19:25
Hi @danielo515 

> What would be cool is to be able to define which template to use for the newly created tiddler.

This would again bloat the TiddlyMap tiddler toolbar button but I could give the user the chance to select a tiddler template when he / she creates a new node from the map. Did you imagine something like this?

**Comment by felixhayashi** [comment] 2015-12-09 23:58
> What would be cool is to be able to define which template to use for the newly created tiddler. This is an important lack of tiddlymap and would help on creating hierarchical layouts.

Hi @danielo515. just wanted to tell you that I implemented this now :) When you add a new tiddler to the map you can choose a template (see screenshots in #192). 

Hope you are fine.
-Felix
