### ISSUE TITLE
Map changes do not invoke wiki autosave

### ISSUE THREAD

**Issue by Peter-Miller** [felixhayashi/TW5-TiddlyMap#36] opened 2015-01-27 14:56 UTC
In Firefox on Windows 8.1 saving map positions changes the color of the Save button but does not invoke the autosave.

**Comment by felixhayashi** [comment] 2015-01-28 10:42
True. This is because position changes impact system tiddlers which are not included by autosave. But I guess you are right, it should autosave, if autosave is enabled.

**Comment by tobibeer** [comment] 2015-01-28 11:36
System tiddlers, too, should trigger autosave: [States And Temporary Tiddlers @ tb5](http://tb5.tiddlyspot.com/#States%20And%20Temporary%20Tiddlers).

**Comment by felixhayashi** [comment] 2015-04-17 17:29
I cannot reproduce this anymore so I'll close this issue now. @Peter-Miller if it is still a problem, please let me know.

**Closed by felixhayashi** 2015-04-17 17:29 UTC
Labels: bug
